// app/topic-post/topic-post.component.ts

import { Component, OnInit, Input } from '@angular/core';
import { TopicsService } from '../topics/topics.service';

@Component({
    selector: 'moc-topic-post',
    providers: [ TopicsService ],
    templateUrl: 'app/topic-post/topic-post.component.html'
})

export class TopicPostComponent implements OnInit {
    @Input() topicPostData;

    posts = [];
    tagName = '';

    constructor(private topicService: TopicsService) {}

    ngOnInit(): void {}
    ngOnChanges(): void {
        if (this.topicPostData.posts) {
            this.posts = this.topicPostData.posts.length ? this.topicPostData.posts : [];
            this.tagName = this.topicPostData.tagName;
        }
    }
}
<article class="card" *ngIf="!posts.length">
    No topics have been loaded yet!
</article>

<h1 class="topic-name">{{tagName}}</h1>

<article class="card" *ngFor="let post of posts">
    <span class="quote" [innerHTML]="post.content.rendered"></span>
    <h1 class="quoted">{{post.title.rendered}}</h1>
</article>

// src/components/TopicPost.vue
<template>
    <div class="topics-wrapper">
        <article class="card" v-if="!posts.length">
            No topics have been loaded yet!
        </article>

        <article class="card" v-if="posts.length"
            v-for="post of posts">

            <span class="quote" v-bind:html="post.content.rendered"></span>
            <h1 class="quoted">{{post.title.rendered}}</h1>
        </article>
    </div>
</template>

<script>
export default {
    name: 'topic-posts',
    props: ['posts']
};
</script>
